[build]
  base    = "wedding-invitation"
  command = "npm run build"
  publish = "wedding-invitation/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
